<div style="background: linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #43a047 100%); padding: 26px 30px; border-radius: 16px; color: #ffffff; margin-bottom: 22px; box-shadow: 0 8px 24px rgba(46, 125, 50, 0.25); border: 1px solid rgba(255, 255, 255, 0.15);">
  <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 14px;">
    <div>
      <span style="background: rgba(255, 255, 255, 0.2); padding: 5px 14px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; display: inline-block; margin-bottom: 10px;">
        Machine Learning Fundamentals
      </span>
      <h1 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif; font-size: 32px; font-weight: 800; letter-spacing: -0.5px;">
        🔢 NumPy Basics for Machine Learning & Numerical Computing
      </h1>
      <p style="margin: 10px 0 0 0; color: #e8f5e9; font-size: 15px; max-width: 650px; line-height: 1.6;">
        High-performance multidimensional array manipulation, mathematical routines, slicing, indexing, and vectorization foundations.
      </p>
    </div>
    <div style="display: flex; align-items: center;">
      <a href="https://colab.research.google.com/github/DebarghyaAich/Machine_Learning_Basics/blob/main/numpy.ipynb" target="_blank">
        <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height: 34px; filter: drop-shadow(0 2px 6px rgba(0,0,0,0.25));" />
      </a>
    </div>
  </div>
  <div style="margin-top: 18px; padding-top: 14px; border-top: 1px solid rgba(255, 255, 255, 0.22); display: flex; gap: 20px; font-size: 12px; color: #c8e6c9; flex-wrap: wrap; font-weight: 500;">
    <span>⚡ <b>Kernel:</b> Python 3.12 (ML Basics)</span>
    <span>📐 <b>Topic:</b> Arrays, Matrices & Linear Algebra</span>
    <span>📂 <b>Author:</b> Debarghya Aich</span>
  </div>
</div>

In [ ]:
import numpy as np

<div style="border-left: 5px solid #2e7d32; padding: 10px 18px; background: rgba(46, 125, 50, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #2e7d32; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🚀</span> 1. Basic Array Creation & Data Types
  </h2>
</div>

In [ ]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [ ]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [ ]:
l1 = [1,2,3,4,5.6,"hi"]
l1

[1, 2, 3, 4, 5.6, 'hi']

In [ ]:
np.array(l1)

array(['1', '2', '3', '4', '5.6', 'hi'], dtype='<U32')

**Array Generation Function**

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1,8,4)

array([1.        , 3.33333333, 5.66666667, 8.        ])

**Random generation Function**

In [ ]:
np.random.rand(10)  #generate numbers between 0 to 1 (normalised)

array([0.47914422, 0.31096411, 0.72625624, 0.61662831, 0.19239125,
       0.76772818, 0.53937127, 0.08734322, 0.65449491, 0.79108638])

In [ ]:
np.random.randn(15)   # generate numbers between -3 to 3 (standardized)

array([-1.85977611,  0.49446354, -1.56609261, -1.41782288, -0.64063308,
       -1.18031576, -0.28671644,  1.09752975, -2.01964964, -0.17851763,
       -1.48909554,  0.98294918, -1.64502171,  2.81249889, -0.34137826])

In [ ]:
np.random.randint(6)  # generate a integer between 0 to that number

1

In [ ]:
np.random.randint(10,30,15)  # start,stop,size

array([25, 14, 23, 17, 18, 10, 12, 28, 11, 16, 23, 26, 25, 26, 24])

**Array Attributes**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

**Array Methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) # column wiae summation

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)  # Row wise summation

array([ 6, 15, 24])

In [ ]:
arr.std()  #standard deviation

np.float64(2.581988897471611)

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.argmax() # index  of the maximum

np.int64(8)

In [ ]:
arr.argmin() # index of the minimum

np.int64(0)

**Reshaping & Resizing**

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])



> `ARRAY INDEXING AND SLICING`

---



**NUmpy Indexing and Slicing of Vectors**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3]  # Indexing

np.int64(14)

In [ ]:
arr[2:6] #Slicing

array([13, 14, 15, 16])

In [ ]:
arr[:5:2]  # start:stop:step

array([11, 13, 15])

**Matrix Indexing And Slicing**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5] # rows

array([26, 27, 28, 29, 30])

In [ ]:
arr[5,1]  #element

np.int64(27)

In [ ]:
arr[:2,1:3]  #slicing

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3:,3:] # Slicing

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [ ]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

**Boolean Indexing**

In [ ]:
arr = np.arange(1,21)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr = arr[arr%2==0] # bool_index = arr%2==0
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])



```
Array Operations
```



Arithmatic Operations


In [ ]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [ ]:
a2-a1

array([5, 5, 5, 5, 5])

In [ ]:
a2*a1


array([ 6, 14, 24, 36, 50])

In [ ]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [ ]:
a2//a1

array([6, 3, 2, 2, 2])

In [ ]:
a2**a1

array([     6,     49,    512,   6561, 100000])

Broadcasting

In [ ]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr = np.arange(1,21).reshape(4,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr*5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [ ]:
arr+5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Deep and Shallow Copy

In [ ]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice = arr[:5]  # Deep copy (slicing)
slice = slice*2
slice

array([ 2,  4,  6,  8, 10])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1=arr # shallow copy

In [ ]:
arr1[0]=100
arr1

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr1 = arr.copy()  # deep copy
arr1*2

array([200,   4,   6,   8,  10,  12,  14,  16,  18,  20])

In [ ]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

Matrix Operations

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [ ]:
a1 @ a2 # Matrix multiplication


array([[19, 22],
       [43, 50]])

In [ ]:
a1.T  #Transpose of a matrix

array([[1, 3],
       [2, 4]])

In [ ]:
a1.dot(a2) # Matrix Multiplication

array([[19, 22],
       [43, 50]])

**Advance Array Operations**

Stacking Array

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

**Splitting Array**

In [ ]:
arr = np.arange(1,21).reshape(4,5)

In [ ]:
np.vsplit(arr,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [ ]:
np.vsplit(arr,4)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]])]

In [ ]:
np.hsplit(arr,5)

[array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]]),
 array([[ 5],
        [10],
        [15],
        [20]])]

# **EXERCISE -- NUMPY**

an array/matrix is given as :


In [ ]:


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Get the shape pf matrix

In [ ]:
data.shape

(5, 3)

Find the average age of students.

In [ ]:
data[:,0].mean()

np.float64(18.4)

Extract Math marks of all students.

In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

Find the highest Science mark.

In [ ]:
data[:,2].max()

np.int64(95)

Get details of the student who scored more than 90 in Math.

In [ ]:
# data[data[:, 1] > 90, 1]
data[data[:,1] > 90]

array([[19, 92, 88]])

Increase Math marks of all students by 5.

In [ ]:
data[:,1]+5

array([90, 97, 81, 70, 95])

Find how many students are younger than 19.

In [ ]:
# data[data[:,0]<19,0].size
data[data[:,0] <19,0].size

3

Calculate the average marks in each subject (column-wise mean).

In [ ]:
np.mean(data[:, 1:], axis=0)

array([81.6, 83.2])

Get data of students who scored at least 80 in both subjects.

In [ ]:
# data[np.all(data[:,1:]>=80,axis=1),1:]
data[np.all(data[:,1:] >=80,axis=1)]

array([[19, 92, 88],
       [20, 90, 85]])

Replace all Science marks < 75 with 0.

In [ ]:
data[data[:, 2] < 75,2]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

### Push Notebook to GitHub Repository
Follow the instructions in the code block below to authenticate and push your notebook to the new repository `MACHINE-LEARNING-BASICS`.

In [ ]:
import os
from google.colab import userdata

# Retrieve GitHub Token from Colab Secrets
try:
    GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
    # Replace with your actual GitHub username
    GITHUB_USERNAME = 'DebarghyaAich'
    REPO_NAME = 'MACHINE-LEARNING-BASICS'

    # Configure Git credentials
    os.environ['GITHUB_TOKEN'] = GITHUB_TOKEN
    os.environ['GITHUB_USERNAME'] = GITHUB_USERNAME
    os.environ['REPO_NAME'] = REPO_NAME

    print("Credentials configured. Please ensure GITHUB_USERNAME is correct and GITHUB_TOKEN exists in Colab secrets.")
except Exception as e:
    print(f"Error getting secret GITHUB_TOKEN: {e}. Please add it to the Secrets (🔑) tab.")

Credentials configured. Please ensure GITHUB_USERNAME is correct and GITHUB_TOKEN exists in Colab secrets.


In [ ]:
%%bash
# Configure user info for Git commits
git config --global user.name "${GITHUB_USERNAME}"
git config --global user.email "${GITHUB_USERNAME}@users.noreply.github.com"

# Initialize local git repository, commit, and push
mkdir -p repo_dir
cd repo_dir
git init

# Download the current notebook's content using colab API
# (Note: In Colab, you can also save directly via File -> Save a copy in GitHub)
# To do it programmatically, we target the runtime notebook file if accessible, or you can copy manual files.


Reinitialized existing Git repository in /content/repo_dir/.git/
